### ISSUE TITLE
Remove 0 value element FeatureVectors

### ISSUE THREAD

**Issue by chucklesoclock** [SLU-TMI/TextMining.jl#20]
It will be easier to calculate length for smoothing

**Comment by mtabor150** [comment]
I modified the FeatureVector type so that if you set a key equal to 0 it will delete the key from the hashtable.  Need to sanitize dictionaries being passed in with 0 value entries since +, -, *, /, // all still allow 0 value entries.

**Comment by Kevin-Damazyn** [comment]
So this is done then right?

**Comment by mtabor150** [comment]
Dictionaries need to be sanitized when they're passed in with 0 value entries still.

**Comment by mtabor150** [comment]
Looks good
