### ISSUE TITLE
DataSet type needs # of unique keys and total # of keys 

### ISSUE THREAD

**Issue by chucklesoclock** [SLU-TMI/TextMining.jl#22]
For Laplace smoothing

**Comment by chucklesoclock** [comment]
I think this is good with the mdata, right?

**Comment by mtabor150** [comment]
I'm not so sure.  It may make sense to just add a unique_keys field.

**Comment by mtabor150** [comment]
In #65 I added features(# keys), and total(# total keys) in the Distribution type to take care of this.
