### ISSUE TITLE
Elbow Method

### ISSUE THREAD

**Issue by mtabor150** [SLU-TMI/TextMining.jl#47]
Make semi automated [elbow method](http://en.wikipedia.org/wiki/Determining_the_number_of_clusters_in_a_data_set#The_Elbow_Method) function to display average distance to centroid using kmeans, given a range of k. 

``` julia
elbow(k_range, vectors, distance_function)  
```

It should print a graph and return a 2xN array of k and the corresponding average distance.

**Comment by Kevin-Damazyn** [comment]
#52

**Comment by Kevin-Damazyn** [comment]
#53
