### ISSUE TITLE
Adding ASCII etc.

### ISSUE THREAD

**Issue by buzzcauldron** [SLU-TMI/TextMining.jl#70]
When I tried to load the programs Mark suggested, I got this error: 

julia> Pkg.add("LightXML")
ERROR: could not spawn setenv(`git rev-parse --git-dir`; dir="/home/seth/.julia/v0.3/METADATA"): no such file or directory (ENOENT)
 in _jl_spawn at process.jl:217
 in spawn at process.jl:348
 in open at ./process.jl:397
 in readbytes at ./process.jl:461
 in dir at pkg/git.jl:10
 in git at pkg/git.jl:16
 in cmd at pkg/git.jl:21
 in readchomp at pkg/git.jl:24
 in branch at pkg/git.jl:56
 in add at pkg/entry.jl:51
 in add at pkg/entry.jl:71
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in __cd#228__ at ./pkg/dir.jl:28
 in add at pkg.jl:20

Any ideas?

**Comment by mtabor150** [comment]
Looks like a problem with how julia or git is setup on your computer. Try executing 

```
git rev-parse --git-dir; dir="/home/seth/.julia/v0.3/METADATA"
```

directly in the terminal window.

**Comment by buzzcauldron** [comment]
(precise)seth@localhost:~$ git rev-parse --git-dir; dir="/home/seth/.julia/v0.3/METADATA"
fatal: Not a git repository (or any of the parent directories): .git

OR

julia> (precise)seth@localhost:~$ git rev-parse --git-dir; dir="/home/seth/.julia/v0.3/METADATA"
ERROR: @localhost not defined

julia> fatal: Not a git repository (or any of the parent directories): .git

**Comment by buzzcauldron** [comment]
Do I need to clone a repository?

**Comment by mtabor150** [comment]
So I think the problem is that "/home/seth/.julia/v0.3/METADATA" does not exist on your computer. Hence the "no such file or directory (ENOENT)" error.  Do the following command in julia 

``` julia
Pkg.status()
```

**Comment by buzzcauldron** [comment]
julia> Pkg.status()
ERROR: unable to read directory METADATA: No such file or directory
 in readdir at ./file.jl:161
 in status at pkg/entry.jl:107
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in status at pkg.jl:28 (repeats 2 times)

**Comment by Kevin-Damazyn** [comment]
@sethstrickland can you check what julia version you are using? if you load the julia REPL it will print it out for you.

**Comment by buzzcauldron** [comment]
_       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.6 (2015-01-08 22:33 UTC)
 _/ |\__'_|_|_|__'_|  |  Official http://julialang.org release
|__/                   |  x86_64-linux-gnu

**Comment by Kevin-Damazyn** [comment]
@sethstrickland that is the correct version, so now we go to git. You have git installed right?

**Comment by buzzcauldron** [comment]
Fixed it. Did 

Pkg.init() and cloned the METADATA

**Comment by Kevin-Damazyn** [comment]
Oh yeah! I remembered doing that but I couldn’t find it in the docs so I figured I was delusional. :-)

**Comment by buzzcauldron** [comment]
So now, am I being dumb:

julia> include("../TextMining.jl")
ERROR: could not open file /home/TextMining.jl
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128

julia> include("./TextMining.jl")
ERROR: could not open file /home/seth/TextMining.jl
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128

julia> include("length/TextMining.jl")
ERROR: could not open file /home/seth/length/TextMining.jl
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128

?

**Comment by buzzcauldron** [comment]
Sorry about all the questions. This syntax is new, so I don't have my fallback commands to try to fix things.

**Comment by Kevin-Damazyn** [comment]
I was here just like you about 3 months ago, this is no problem. haha
ok so there are a couple ways to figure this out.
1. do you know your way around the command line?
if so, go (cd) to the SLU-TextMining folder
open julia
then use the include("./src/TextMining.jl") line
if not
2. Open the folder in windows explorer
right click on the SLU-TextMining folder
select open in gui-bash (or something like that)
run julia from inside this folder
then do the include("./src/TextMining.jl") line

**Comment by mtabor150** [comment]
You have to navigate to where you cloned the data from github to and then you can use 

``` julia
include ("./TextMining.jl")
```

**Comment by buzzcauldron** [comment]
Awesome. Got it for src. Now when I run

julia> include("./test/TextMining.jl")
ERROR: could not open file /home/seth/Desktop/TextMining.jl-master/test/TextMining.jl
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128

that happens.

**Comment by mtabor150** [comment]
There is no TextMinging.jl file in the test directory.  If you want to run the tests you have to do the following:

``` julia
include("./test/runtests.jl")
```

That will load in the tests as well as loading in everything else.  Then you can do

``` julia
run_tests()
```

which will execute all the tests.  Note that Julia freaks out if you try to reload types so do
include("./test/runtests.jl") or include("./src/TextMining.jl"), but not both.

**Comment by Kevin-Damazyn** [comment]
So there is no TextMining.jl in the test folder.
 The only thing you need to load in the test folder is runtests.jl file.
Be careful though because you will run into an error if you load both files in.
The TextMining.jl file is to use the application.
The runtests.jl is to use the function runtests() which will just run through the created tests we made for the project.
So if you want to play with the applications, load TextMining.jl
if you want to run the tests, load runtests.jl

**Comment by mtabor150** [comment]
Jinx you owe me a coke @Kevin-Damazyn .

**Comment by Kevin-Damazyn** [comment]
Alright @mtabor150. I am going to let you take it from here. :-)
I still have to write my conclusion to this C-at-best paper haha
I'll buy your coke the same time I buy Charlie his shot.

**Comment by mtabor150** [comment]
I'll take a shot instead.

**Comment by buzzcauldron** [comment]
Perfect. You guys @mtabor150 @Kevin-Damazyn so fly.
