### ISSUE TITLE
Fix Clusters so that they are allowed to contain Clusters

### ISSUE THREAD

**Issue by drawkward** [SLU-TMI/TextMining.jl#81]
When describing what was desired for hclust, it was noted that the end result would be a cluster of clusters (which could be unwrapped like a tree).  However, the Cluster type only accepts FeatureVector types as values.  We need to be able to cluster together one or more clusters in order for hclust to return the desired result.

**Comment by mtabor150** [comment]
It shouldn't be a cluster of clusters, it should be a binary tree where every leaf is a feature vector and the nodes are the centroids or other method of distance between the subtrees.

**Comment by Kevin-Damazyn** [comment]
It should return something like [this](http://borel.slu.edu/crubadan/crubadan.svg)
Note: the picture is huge! zoom out or scroll to the left until you see color. :)

**Comment by mtabor150** [comment]
[Here is the link to Dr. Scannell's blog-post about that image.](http://indigenoustweets.blogspot.com/2011/12/1000-languages-on-web.html)
