### ISSUE TITLE
\2223

### ISSUE THREAD

**Issue by ljekersey** [SLU-TMI/TextMining.jl#98]
\2223 appears to show up in a huge number of our words. I think this is the divides symbol, "|". Does anyone have a guess as to why?

**Comment by Kevin-Damazyn** [comment]
Can you tell us a text whre this comes up in?

**Comment by ljekersey** [comment]
Yeah, I'll try to find an example. It comes up a lot in a spreadsheet of
word types, but I will try to find it in an actual file.

[image: Inline image 1]
